Add storage support for limit
AY1920S1-CS2113T-F11-2/main pull request #144
Opened 2019-10-17 17:27 UTC by yetong1895

Storage support is added for limit(load is working, save not yet)
added basic listing for limit I.E. "limits" to list.

2019-10-18 03:09 UTC, tatayu approved these changes

2019-10-18 08:13 UTC, omupenguin approved these changes

2019-10-18 08:13 UTC, omupenguin reviewed
Can add duke.txt to .gitignore?

2019-10-18 08:15 UTC, Weng-Kexin approved these changes

2019-10-18 08:17 UTC, omupenguin commented on src/main/java/dolla/command/RemoveCommand.java
> +    public RemoveCommand(String mode, String taskNumStr) {
Let's not use 'taskNumStr' since that's the old system

2019-10-18 08:22 UTC, omupenguin requested changes
Refer to comments

2019-10-19 17:10 UTC, yetong1895 commented
> Can add duke.txt to .gitignore?

added

2019-10-20 10:11 UTC, omupenguin approved these changes

2019-10-20 16:14 UTC, merged