Added removeLimit feature
AY1920S1-CS2113T-F11-2/main pull request #146
Opened 2019-10-20 05:19 UTC by Weng-Kexin

Added removeLimitCommand to remove limits and modified UG accordingly

2019-10-20 16:15 UTC, yetong1895 requested changes
Conflicting files
src/main/java/dolla/command/ShowListCommand.java
src/main/java/dolla/parser/LimitParser.java
src/main/java/dolla/task/Limit.java

Resolved

2019-10-21 10:21 UTC, tatayu approved these changes

2019-10-21 11:11 UTC, Weng-Kexin commented
conflicts resolved

2019-10-21 13:45 UTC, yetong1895 approved these changes

2019-10-22 05:23 UTC, omupenguin approved these changes

2019-10-22 05:23 UTC, merged