Added and updated some java documentations.
AY1920S1-CS2113T-F11-2/main pull request #159
Opened 2019-10-23 17:47 UTC by omupenguin

2019-10-24 08:12 UTC, tatayu approved these changes

2019-10-24 10:02 UTC, Weng-Kexin requested changes
### Conflicting files:
src/main/java/dolla/Ui.java
src/main/java/dolla/parser/Parser.java

2019-10-25 11:27 UTC, omupenguin commented
@Weng-Kexin Resolved!

2019-10-26 07:36 UTC, yetong1895 approved these changes

2019-10-27 10:36 UTC, Weng-Kexin approved these changes

2019-10-27 10:36 UTC, merged