Added documentation
AY1920S1-CS2113T-F11-2/main pull request #161
Opened 2019-10-24 07:37 UTC by tatayu

2019-10-24 08:14 UTC, yetong1895 approved these changes

2019-10-24 10:08 UTC, Weng-Kexin requested changes
some javadocs are not required (eg. get() methods, i/o related methods)

refer to: [this](https://nuscs2113-ay1920s1.github.io/website/schedule/week9/topics.html#w9-4-writing-developer-documents) (akshay's lecture on 11/10 mentioned it too)

2019-10-24 12:54 UTC, Weng-Kexin approved these changes

2019-10-25 03:16 UTC, omupenguin approved these changes

2019-10-25 03:16 UTC, merged